### ISSUE TITLE
where is amun malware save!

### ISSUE THREAD

**Issue by jjjan** [zeroq/amun#3]
after  six month of running MHN . i checked "md5sum" folder of amun honeypot and surprised. there is no malware save. do you know why ?
i installed Amun honeypot (not using MHN)before and after two days i got malware sample.

**Comment by zeroq** [comment]
hi jjjan, i haven't played around with MHN much, but according to your problem description it seems to have something to do with the connectors to MHN. Do your Amun log files provide any information or errors ?
